# Generated by Django 4.2.2 on 2023-06-25 18:26

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_remove_following_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=feed.models.get_user_profile_photo_path),
        ),
    ]
