# Generated by Django 4.2.2 on 2023-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_post_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', to='feed.userprofile'),
        ),
    ]
