# Generated by Django 4.2.2 on 2023-07-09 12:48

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_alter_post_viewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default=None, upload_to=feed.models.get_user_profile_photo_path),
        ),
    ]
