# Generated by Django 4.2.2 on 2024-02-28 19:21

from django.db import migrations, models
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='/profile_photos/admin/logo.jpg', upload_to=feed.models.get_user_profile_photo_path),
        ),
    ]
